import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
const context = await browser.newContext({ viewport: { width: 1512, height: 1100 }, locale: 'zh-TW' });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const base = process.env.APP_URL || 'http://127.0.0.1:4173';
const artifacts = new URL('./artifacts/', import.meta.url).pathname;
await mkdir(artifacts, { recursive: true });
const clickAction = action => page.locator('[data-action="' + action + '"]').first().click();
try {
  await page.goto(base);
  await page.getByRole('heading', { name: '一起排好，下一週。' }).waitFor();
  assert.equal(await page.locator('.shift-cell').count(), 14);
  await page.screenshot({ path: artifacts + 'desktop.png', fullPage: true });
  const removed = await page.locator('[data-action="remove-assignment"]').first().getAttribute('data-member');
  await clickAction('remove-assignment');
  await clickAction('publish');
  assert.match(await page.locator('#dialog').innerText(), /目前還不能發布/);
  await clickAction('close-dialog');
  await clickAction('undo');
  await clickAction('publish');
  await clickAction('confirm-publish');
  assert.equal(await page.locator('.version-row').count(), 1);
  await clickAction('remove-assignment');
  await page.locator('[data-action="add-assignment"][data-member="' + removed + '"]').click();
  assert.match(await page.locator('.assigned-person').first().locator('..').innerText(), /已鎖定/);
  await page.reload();
  await page.getByRole('heading', { name: '一起排好，下一週。' }).waitFor();
  assert.equal(await page.locator('[data-action="undo"]').isEnabled(), true);
  await clickAction('solve');
  await page.locator('.candidate-option').first().waitFor({ timeout: 10000 });
  assert.ok(await page.locator('.candidate-option').count() > 0);
  await clickAction('candidate');
  assert.match(await page.locator('.preview-banner').innerText(), /預覽中/);
  await clickAction('apply-candidate');
  await clickAction('people');
  assert.equal(await page.locator('.people-schedule tbody tr').count(), 6);
  await clickAction('coverage');
  await page.locator('[data-action="nav"][data-tab="inputs"]').click();
  await clickAction('edit-input');
  await page.locator('#input-note').fill('週三 晚班 不可排\n週五 早班 希望排');
  await clickAction('parse-note');
  assert.match(await page.locator('#note-preview').innerText(), /規則預覽/);
  await clickAction('apply-note');
  await page.getByRole('button', { name: '確認本期需求', exact: true }).click();
  await clickAction('review');
  await clickAction('freeze');
  assert.match(await page.locator('#main').innerText(), /需求已重新凍結/);
  await clickAction('blank-draft');
  await clickAction('confirm-blank-draft');
  await clickAction('solve');
  await page.locator('.candidate-option').first().waitFor({ timeout: 10000 });
  await clickAction('candidate');
  await clickAction('apply-candidate');
  await clickAction('publish');
  await clickAction('confirm-publish');
  assert.equal(await page.locator('.version-row').count(), 2);
  await page.locator('[data-action="version"][data-number="1"]').click();
  assert.match(await page.locator('.preview-banner').innerText(), /已發布 v1/);
  assert.equal(await page.locator('[data-action="remove-assignment"]').first().isDisabled(), true);
  await clickAction('show-draft');
  const [csv] = await Promise.all([page.waitForEvent('download'), clickAction('export-csv')]);
  assert.ok(csv.suggestedFilename().endsWith('.csv'));
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('#group-select-mobile').isVisible(), true);
  assert.equal(await page.locator('.schedule').isVisible(), false);
  assert.equal(await page.locator('.mobile-agenda').isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: artifacts + 'mobile.png', fullPage: true });
  await page.locator('h1').click();
  await page.screenshot({ path: artifacts + 'mobile-viewport.png', fullPage: false });
  await page.locator('[data-action="nav"][data-tab="inputs"]').click();
  await clickAction('edit-input');
  assert.equal(await page.evaluate(() => document.querySelector('#dialog').scrollWidth <= document.querySelector('#dialog').clientWidth), true);
  await clickAction('close-dialog');
  await page.setViewportSize({ width: 1512, height: 1100 });
  await clickAction('new-group');
  await page.locator('#group-form [name="name"]').fill('<img src=x onerror=alert(1)> 測試群組');
  await page.locator('#group-form button[type="submit"]').click();
  await clickAction('new-member');
  await page.locator('#member-form [name="name"]').fill('小新');
  await page.locator('#member-form button[type="submit"]').click();
  await clickAction('new-period');
  await page.locator('#period-form [name="name"]').fill('驗收單日');
  await page.locator('#period-form [name="days"]').fill('1');
  await page.locator('#period-form [name="shiftRequired1"]').fill('0');
  await page.locator('#period-form button[type="submit"]').click();
  await clickAction('edit-input');
  await clickAction('fill-yes');
  await page.getByRole('button', { name: '確認本期需求', exact: true }).click();
  await clickAction('review');
  await clickAction('freeze');
  await clickAction('solve');
  await page.locator('.candidate-option').first().waitFor({ timeout: 10000 });
  await clickAction('candidate');
  await clickAction('apply-candidate');
  await clickAction('publish');
  await clickAction('confirm-publish');
  assert.equal(await page.locator('.version-row').count(), 1);
  assert.equal(await page.locator('img[src="x"]').count(), 0);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload();
  await context.setOffline(true);
  await page.reload();
  await page.getByRole('heading', { name: '一起排好，下一週。' }).waitFor();
  assert.equal(await page.locator('.version-row').count(), 1);
  await context.setOffline(false);
  assert.deepEqual(errors, []);
  console.log('PASS: desktop, mobile, worker, editing, locks, history, confirmed notes, stale input, immutable publishing, CSV, group creation, XSS escaping, offline reload.');
} finally {
  if (errors.length) console.error(errors);
  await browser.close();
}
