from pathlib import Path
import json,hashlib
import pandas as pd
R=Path(__file__).resolve().parent;BASE=R.parent
def save(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False))
def main():
    raw=json.loads((R/'source_timing_audit.json').read_text());assert raw['passed']
    sensitivity=json.loads((R/'reconstruction_summary.json').read_text())
    d=pd.read_csv(R/'eps_sensitivity_by_case.csv');selected=pd.read_pickle(R/'selected_cases.pkl');dates=selected.set_index('CaseID').EffectiveTimestamp
    assert len(d)==20 and set(d.CaseID)==set(selected.CaseID)
    lines=['# v20：20筆EPS資料核對','', '本輪已完成10筆一般案例與10筆極端案例的資料抽查。原始數字與時點核對通過，但找到累計EPS相減不等於正式單季EPS的具體案例。這是資料查核結果，尚未重訓或證明它能解釋先前的Sharpe。','', '## 最重要的發現','', '### 1. 原始讀取與時點沒有在本次樣本中查到錯誤','', '20筆事件的87筆去重來源、1,218項欄位核對均與原始JPX ZIP相符。100次來源引用均屬正確股票、會計基礎與季度，並且是當時最新的正常財報。18筆在15:00或之後公布，均延至下一交易日使用。這只證明資料忠實於原始CSV與既定時點規則，不等於EPS拆季定義正確。','', '### 2. EPS直接差分，已有正式文件證實會出錯','', 'E05，中國塗料（4617），2019年10-12月單季：','', '| 項目 | 舊程式累計EPS相減 | 公司正式單季EPS |','|---|---:|---:|','| 本季EPS | 13.31 | 13.39 |','| 去年同季EPS | 0.01 | 0.12 |','| 依指定公式計算年增率（比率） | 1330.00 | 110.5833 |','| 換算百分比 | 133,000% | 11,058.33% |','', '兩個年增比率相差約12倍。直接相減累計EPS隱含了每一期分母可比的假設；EPS使用各期間平均股數，股數變動或公布值捨入會使差分失真。EPS的分子、分母與可能受股本變動影響的原則，參見[IFRS IAS 33](https://www.ifrs.org/issued-standards/list-of-standards/ias-33-earnings-per-share/)。此原則說明機制，個案判定以公司文件為準。','', '公司[2020-02-12季度報告](https://www.cmp.co.jp/IR/2020/2020_f-report_3q.pdf) PDF第4頁直接列出13.39與0.12。該文件晚於2020-01-31原訊號日；本輪用它證明拆季近似有問題，不把它當作1月31日已知的資料回填。','', '### 3. 來源表與公司原始公告也有不一致', '', 'N09，Carna Biosciences（4572），2021年第二季累計EPS：本地及原始JPX CSV的SourceRow 86273是-62.50，公司[2021-08-06原始公告](https://www.carnabio.com/output/irlibrary/682_ja.pdf)首頁及8月10日季報卻都是-62.56，平均股數同為12,411,031。原因尚未確定，不能將快取比對原CSV通過當成公司數字已驗證。', '', '公司[2021-11-09季度報告](https://www.carnabio.com/output/irlibrary/688_ja.pdf)直接列本季單季EPS -31.68；本地使用-62.50差分算成-31.74。只把該累計輸入改成公告的-62.56，就會得到-31.68。因此這個差異不能全部歸因於股數或累計EPS非可加性。官方去年單季也另列-20.29，本地為-20.33；兩個差異需分開核對。', '', '### 4. 極端值也可能是真的低基期，或之後才被更正','', '選出的10筆極端事件，舊版去年同季EPS分母絕對值都不超過0.09。其中4筆是第一季直接EPS，6筆是累計相減。即使讀取和相減計算沒有程式錯誤，低基期與兩位小數精度仍會放大成長率。','', 'E07，2884，另有[2022-05-11正式更正](https://www2.jpx.co.jp/disc/28840/140120220511539996.pdf)，更正2021-07-15發布的財报：當季／去年同季EPS改列10.69／1.06，本地舊版是9.84／0.01。這是後來的更正證據，不能倒填2021年的模型資訊。原版是否取得及其他文件查核範圍，見逐案來源檔。','', '## 抽樣方法','', '一般組：兩比率絕對值均不超過2，按年份／季度分層隨機抽10家公司，固定種子20260915。極端組：兩比率任一絕對值超過100，取v19平方誤差最高的10家公司。均來自v19的2019-2021正式評估事件。','', '這是查錯用途的抽樣，不能用20筆中的問題比例推估所有股票。一般组限制在±200%以內，也不能代表所有100倍以內的事件。10筆極端案例合計占v19完整評估平方誤差約78.86%，因此值得優先檢查，但這不代表全部誤差都能修掉。','', '## 全部20筆案例','', '下列「股數敏感度」只測試分母變動的可能影響，不是官方修正後EPS。單位為比率，1代表100%。','', '| 案例 | 代碼 | 公布日 | 舊季增 | 舊年增 | 股數敏感度年增 |','|---|---:|---|---:|---:|---:|']
    for e in d.itertuples():lines.append(f'| {e.CaseID} | {e.Code} | {dates[e.CaseID].date()} | {e.OriginalQoQ:+.4f} | {e.OriginalYoY:+.4f} | {e.ShareAdjustedYoYSensitivity:+.4f} |')
    lines+=['', '一般10筆在這個股數敏感度計算中，季增／年增方向都未翻轉；最大的年增變動约0.33個百分點。這是一個局部的穩定性觀察，不代表20筆或整批EPS都已被證明精確。','', '## 敏感度怎麼計算，為什麼不能直接當真值','', '以兩期累計平均股數 S_k、S_prev 及累計天數 D_k、D_prev，暫估單季平均股數：','', 'S_quarter = (D_k × S_k - D_prev × S_prev) / (D_k - D_prev)。','', '再用公布累計EPS隱含的分子差：','', 'EPS_quarter_sensitivity = (EPS_k × S_k - EPS_prev × S_prev) / S_quarter。','', '這需要兩期採一致股數加權口徑、股票分割／重編基礎與可相減的EPS分子。原始資料沒有證明所有前提，因此只列為敏感度。另列 Profit 差分除以股數的結果也只是交叉檢查；Profit 在原始表中往往已按百萬單位捨入，不能當完整精度的EPS分子。','', 'E06、E07可見Profit欄為0、EPS卻是0.01。這可能是顯示精度差異，不能直接把原EPS改成0。E10的累計Profit差為0，也不能據此斷言該季沒有獲利。','', '若額外假設EPS按0.01四捨五入、公布股數精確且口徑一致，可傳播±0.005的條件式精度範圍。它不是統計信賴區間或真實EPS保證範圍。E05的年增敏感度約93.60至110.06倍，跨越100倍門檻；E10的基期敏感度跨0，無法給出穩定有限的年增範圍。','', '點估計沒有使任何一筆跨越100倍門檻，不代表門檻判定毫無不確定性。','', '## 後續應只先處理什麼','', '先修EPS資料定義，再用相同g、樣本規則與訓練方式重跑原比較。資料規則應區分：直接披露的單季EPS、可核對股數及口徑的估算、不能可靠還原的缺值；每個值保留其實際發布時間與版本。','', '基期接近零的成長率也需獨立標記其精度與不穩定性。具體門檻或替代訊號應另做受控比較，本輪沒有選新門檻、改loss或加交叉項。','', '目前仍不能說資料修正一定會提高Sharpe。v18/v19及其他使用舊EPS拆季的結果，應解讀為舊資料定義下的結果。純價量v7不含EPS，正式基準保持原樣。','', '## 外部文件覆蓋與未完成的核對', '', '兩份逐案來源檔涵蓋20個案例，但不是20份完整的公司歷史稽核。N05主要以後續報告的官方搜尋摘要確認；部分其他案例只確認累計值，未取得全部舊基期原件或独立單季EPS。晚出年報、季報與更正都標注日期，不能因網址可讀就推定當時可用。', '', '## 來源與檔案','', '- selected_cases.csv：20筆案例、選取規則及原始引用。','- source_timing_audit.json、source_raw_field_checks.csv、source_reference_timing_checks.csv：原ZIP與時點核對。','- quarter_reconstruction_details.csv、eps_sensitivity_by_case.csv：60個季度拆季核對與20個成長率比較。','- rounding_sensitivity_intervals.csv：精度敏感度，非信賴區間。','- ordinary_primary_sources.json/md、extreme_primary_sources.json/md：公司／JPX文件逐案查核、網址、確認值與未解事項。','- 所有原始財報快取與歷史預測未被改寫，本輪未重新計算Sharpe。']
    (R/'JPX-v20-eps-data-audit-report.md').write_text('\n'.join(lines)+'\n')
    result=dict(version='v20',task='20-case EPS data audit',selected_cases=20,source_fields_checked=1218,source_timing_passed=True,confirmed_material_eps_subtraction_mismatch=dict(case='E05',code=4617,old_current_eps=13.31,old_year_eps=.01,official_current_eps=13.39,official_year_eps=.12,official_document_date='2020-02-12',original_event_date='2020-01-31',source='https://www.cmp.co.jp/IR/2020/2020_f-report_3q.pdf'),later_revision_case='E07',source_value_mismatch=dict(case='N09',source_row=86273,raw_csv_eps=-62.50,issuer_pdf_eps=-62.56,issuer_date='2021-08-06',cause='unresolved'),sensitivity_only=True,models_retrained=False,active_baseline='v7')
    save(R/'results.json',result)
    sources=[R/'selected_cases.pkl',R/'selected_source_records.csv',R/'reconstruct.py',R/'source_timing_audit.py',R/'source_timing_audit.json',R/'audit_plan.md',R/'report.py',BASE/'jpx_v19_qoq_predict_yoy_20260915/predictions.pkl']
    save(R/'manifest.json',dict(source_sha256={str(p.relative_to(BASE)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sources}))
    print(json.dumps(result,ensure_ascii=False))
if __name__=='__main__':main()
